# Generated by Django 4.2.1 on 2023-06-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_color_product_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingdetails',
            options={'verbose_name': 'Shipping detail'},
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
