# Generated by Django 4.2.1 on 2023-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_shippingdetails_options_shippingdetails_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=200),
        ),
    ]
