# Generated by Django 4.2.1 on 2023-06-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_shippingdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='phone_number',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
