# Generated by Django 4.2.1 on 2023-06-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delivery_shippingdetails_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.currency'),
        ),
    ]
