# Generated by Django 4.2.1 on 2023-06-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_orderitem_size_orderitem_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sizes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.size'),
        ),
    ]
