# Generated by Django 4.2.1 on 2023-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_order_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
